version: '2'

services:
    api:
        build: .
        depends_on:
            - db
        ports:
            - "8080:8080"
        links:
            - db
        volumes:
            - ".:/usr/src/app"

    db:
        image: mongo
        ports:
            - "27017:27017"
            - "27018:27018"
            - "27019:27019"
            - "28017:28017"
